# Generated by Django 6.0.3 on 2026-03-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedfile',
            old_name='size',
            new_name='file_size',
        ),
        migrations.RenameField(
            model_name='storedfile',
            old_name='uploaded_at',
            new_name='uploaded_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
