# Generated by Django 6.0.3 on 2026-10-06 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_folders_quota_share_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("total_size", models.PositiveBigIntegerField()),
                ("received_bytes", models.PositiveBigIntegerField(default=0)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="folder",
            name="unique_folder_name_in_parent",
        ),
        migrations.RemoveConstraint(
            model_name="folder",
            name="unique_folder_name_in_root",
        ),
        migrations.AddField(
            model_name="folder",
            name="deleted_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="deleted_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_time__isnull", True)),
                fields=("owner", "parent", "name"),
                name="unique_active_folder_name_in_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_time__isnull", True), ("parent__isnull", True)
                ),
                fields=("owner", "name"),
                name="unique_active_folder_name_in_root",
            ),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="storage.folder",
            ),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
