# Generated by Django 6.0.3 on 2026-10-08 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_share_owner(apps, schema_editor):
    ShareLink = apps.get_model("storage", "ShareLink")
    for link in ShareLink.objects.select_related("file"):
        link.owner_id = link.file.owner_id
        link.save(update_fields=["owner"])


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_trash_uploads"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("used_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="sharelink",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_links",
                to="storage.folder",
            ),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="max_downloads",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="password_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="totp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="totp_last_step",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_links",
                to="storage.storedfile",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("file__isnull", False), ("folder__isnull", True)),
                    models.Q(("file__isnull", True), ("folder__isnull", False)),
                    _connector="OR",
                ),
                name="share_link_has_one_target",
            ),
        ),
        migrations.AddField(
            model_name="recoverycode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recovery_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # 既有的分享連結都是分享檔案，擁有者就是檔案的擁有者
        migrations.RunPython(fill_share_owner, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="sharelink",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
