# Generated by Django 6.0.3 on 2026-10-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_two_factor_share_options_dedupe"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("created_time", models.DateTimeField()),
                ("replaced_time", models.DateTimeField(auto_now_add=True)),
                (
                    "stored_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="storage.storedfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_time"],
            },
        ),
    ]
