# Generated by Django 6.0.3 on 2026-10-09 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_file_versions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "登入"),
                            ("login_failed", "登入失敗"),
                            ("two_factor_failed", "驗證碼錯誤"),
                            ("logout", "登出"),
                            ("password_change", "變更密碼"),
                            ("two_factor_enable", "啟用兩步驟驗證"),
                            ("two_factor_disable", "停用兩步驟驗證"),
                            ("recovery_codes", "重新產生備用碼"),
                            ("upload", "上傳"),
                            ("update", "上傳新版本"),
                            ("trash", "移到回收筒"),
                            ("restore", "從回收筒還原"),
                            ("purge", "永久刪除"),
                            ("move", "移動"),
                            ("version_restore", "還原舊版本"),
                            ("share_create", "建立分享連結"),
                            ("share_revoke", "撤銷分享連結"),
                            ("share_download", "分享連結被下載"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=255)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_time", "-pk"],
            },
        ),
    ]
